### PR TITLE
bug: deselecting a checkpoint breaks the dashboard in certain scenarios

### LINKED ISSUE #747: (Bug) Deselecting a checkpoint breaks the explorer dashboard
If a checkpoint is deselected while any of its source/target is selected, the dashboard breaks.

To reproduce

1. Open the [URL](https://www.aem.live/tools/oversight/explorer.html?domain=business.adobe.com&filter=&view=month&=performance&checkpoint=click&click.source=button.con-button&domainkey=incognito&conversion.checkpoint=click) in the tab (replace `incognito` with the correct domain key)
2. Deselect the click checkpoint.

Expected:
The dashboard should work and should show the correct data.

Result:
The dashboard breaks. To fix it one needs to update the URL and remove the click.source attribute from the URL.

### PR DESCRIPTION
**Pull request by vdua**
fixes #747 

Try the same steps with this URL (replace `incognito` with the correct domain key)

https://deselect-checkpoint--helix-website--vdua.aem.live/tools/oversight/explorer.html?domain=business.adobe.com&filter=&view=month&=performance&checkpoint=click&click.source=button.con-button&domainkey=incognito&conversion.checkpoint=click

## Description

We remove the source/target filters from the state if the checkpoint is not present in the filter.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] I have signed the [Adobe Open Source CLA](https://opensource.adobe.com/cla.html).
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

File: tools/oversight/slicer.js [hunk 1]
```diff
@@ -36,7 +36,7 @@ const API_ENDPOINT = BUNDLER_ENDPOINT;
 const elems = {};
 
 const dataChunks = new DataChunks();
-
+window.dataChunks = dataChunks;
```
Comment (vdua) [inline tools/oversight/slicer.js:39]: need to remove that

**Review by langswei — APPROVED** [review]
looks good and tested successfully - thanks!
