### PR TITLE
[#331] doc page mobile in-page nav ui fix & other fixes

### LINKED ISSUE #331: Mobile: more compact in-page navigation
> feels like we could make better use of the screen estate on mobile: the top third of the screen is used for breadcrumbs, several navigational elements (hamburger, menu dropdown), search bar and back link… wondering if we need all of that on mobile or if it could be hidden/folded away…
image_480

### PR DESCRIPTION
**Pull request by snowiewdev**
#331 Fix for issue on mobile: more compact in-page navigation 

Test Urls
Doc Detail:
Before: https://main--helix-website--adobe.hlx.page/docs/authoring
After: https://redesign-bug-fix--helix-website--adobe.hlx.page/docs/authoring

### CODE REVIEW

File: blocks/header/header.js [hunk 1]
```diff
@@ -249,7 +249,7 @@ class Gnav {
       submenuLink.setAttribute('target', returnLinkTarget(submenuLink.href));
 
       // TODO: temp fix for status.live, can be remove if subdomain is supported
```
Comment (trieloff) [inline blocks/header/header.js:251]: We can remove this entirely, I've fixed it with a redirect

**Review by trieloff — APPROVED** [review]

**Comment by trieloff** [comment]
Screenshot 2023-07-03 at 10 17 08

What if we moved the search bar into the top navigation (and made it scroll away, so that it does not take away screen estate on the small phone display)?

**Comment by snowiewdev** [comment]
Hey @trieloff, I've moved the search bar on mobile to header menu instead, that way when the user try to navigate and open the menu, they can be able to search there instead and doesn't take up space in the doc detail page. Let me know if that works or need further adjustment. Thank you!

Video Capture: https://www.awesomescreenshot.com/video/18894378?key=b9ac9497375d2f8c7d49ac64739e66a7

**Review by nicolerego — APPROVED** [review]
